language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start my.conf.js --single-run
services:
  - xvfb
before_install:
    - export DISPLAY=:99.0
    - export CHROME_BIN=chromium-browser
before_script:
    - npm install
